### Create a new use / signup

POST http://localhost:3000/auth/signup
content-type: application/json

{
     "email": "nhlakah@gmail.com",
     "password": "12345abc"
}
### signin

POST http://localhost:3000/auth/signin
content-type: application/json

{
     "email": "nhlakah@gmail.com",
     "password": "12345abc"
}
### ID
GET http://localhost:3000/auth/6

### current user
GET http://localhost:3000/auth/whoami

### signout user
POST http://localhost:3000/auth/signout

### 
GET http://localhost:3000/auth?email=ask2323@gmail.com

### 
DELETE http://localhost:3000/auth/5

### 

PATCH http://localhost:3000/auth/2
content-type: application/json

{
     "email": "ask@YAHOO11.com"
}

# ### Set a color
# GET http://localhost:3000/auth/colors/green

# #### Get the color
# GET http://localhost:3000/auth/colors


### Create Reports
POST http://localhost:3000/reports
content-type: application/json

{
     "make": "nisan",
     "model": "whateva",
     "year": 1981,
     "mileage": 1000000,
     "lng": 0,
     "lat": 0,
     "price": 500000
}
